# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'Tabour' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Tabour
  pod 'SwiftKeychainWrapper'
  pod 'SDWebImage'
  pod 'Alamofire'
  pod 'iProgressHUD'
  pod 'GooglePlaces'
end
